@MonitoringDumpTruck_HostAddress = http://localhost:5233

GET {{MonitoringDumpTruck_HostAddress}}/api/DumpTrucks
Accept: application/json

###

GET {{MonitoringDumpTruck_HostAddress}}/api/dumptrucks/4
Accept: application/json